version: "3.8"
services:
  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - /opt/app_data/grafana:/var/lib/grafana
      - /opt/home-iac/dockerized_apps/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN=ergani
      - GF_SERVER_HTTP_PORT=3000
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    networks:
      - home_network

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - /opt/app_data/prometheus:/etc/prometheus
      - /opt/home-iac/dockerized_apps/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=30d'
    restart: always
    networks:
      - home_network

networks:
  home_network:
    external:
      name: the_home_network
