version: "3.8"
services:
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    volumes:
      - /opt/temple-iac/dockerized_apps/nginx.conf:/etc/nginx/nginx.conf
      - /opt/temple-iac/temple.html:/etc/nginx/temple.html
    ports:
      - 80:80
      - 443:443
    networks:
      - temple_network

networks:
  temple_network:
    name: the_temple_network
