version: "3.8"
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Istanbul
    volumes:
      - /opt/app_data/jackett/data:/config
      - /opt/app_data/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - home_network

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Istanbul
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - /opt/app_data/qbittorent/data:/config
      - /media/oculus_disk/blackhole:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - home_network

  jellyfin:
    image: linuxserver/jellyfin:latest
    hostname: jellyfin
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Istanbul
      - JELLYFIN_PublishedServerUrl=oculus/jellyfin
    volumes:
      - /opt/app_data/jellyfin/library:/config
      - /media/oculus_disk:/data
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - home_network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /opt/app_data/sonarr/data:/config
      - /media/oculus_disk:/oculus_disk #optional
      - /media/oculus_disk/blackhole:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - home_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /opt/app_data/radarr/data:/config
      - /media/oculus_disk:/oculus_disk #optional
      - /media/oculus_disk/blackhole:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - home_network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /opt/app_data/bazarr/data:/config
      - /media/oculus_disk:/oculus_disk #optional
      - /media/oculus_disk/blackhole:/downloads #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - home_network
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /opt/app_data/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - home_network
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Etc/UTC
    ports:
      - 8191:8191
    restart: unless-stopped 
    networks:
      - home_network

networks:
  home_network:
    external:
      name: the_home_network