version: "3.8"
services:
  jackett:
    image: linuxserver/jackett:0.22.457
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - /opt/app_data/jackett/data:/config
      - /opt/app_data/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - temple_network

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - /opt/app_data/qbittorent/data:/config
      - /opt/app_data/qbittorent/blackhole:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - temple_network

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.9.9
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - JELLYFIN_PublishedServerUrl=jellyfin.temple
    volumes:
      - /path/to/jellyfin/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - temple_network

networks:
  temple_network:
    external:
      name: the_temple_network